settings:
  no_session: # 세션 체크 제외 페이지 
    - /login/login.do
    - /login/join.do
  no_session_pattern: # 세션 체크 제외 페이지 패턴
    - "/(.*)/ajax.(.*)Process.do"
  fruits:
    - name: banana
      color: yellow
    - name: apple
      color: red
    - name: water melon
      color: green